# Download the tomcat image
From tomcat:8.5

# move files inside the destination location
COPY application.properties /etc/verve/sdkconfig/
COPY ../../../build/libs/SDKConfigService.war webapps/

#Copy the environment to bin where catalina.sh is located
#Has the password, and username for the database
#This can be extracted from System.getProperty("value")
COPY setenv.sh bin/

# Add required permissions for tomcat
RUN chmod +x bin/*.sh

# copy tomcat startup script
COPY start.sh ./

# set permissions for startup script
RUN chmod +x start.sh

# expose default tomcat port
EXPOSE 8080

# Start tomcat
#CMD ["./start.sh"]

CMD ["catalina.sh", "run"]